sudo: false

language: node_js
node_js:
  - '10.16'
before_install:
  - echo 'export const ENV = {parseAppId:"",parseJavascriptKey:"",parseServerUrl:"",parseMasterKey:"" }' > src/app/app.constant.ts
install:
  - npm install -g ionic@3.20.1
  - npm install -g cordova@8.1.1
  - npm install -g codecov

script:
  - npm ci --no-optional
  - npm run website:build
  - codecov