sudo: false

language: node_js
node_js:
  - '10.16'

install:
  - npm install -g codecov

script:
  - npm install
# - npm run test && codecov
#  - npm run test-coverage
  - ionic cordova platform remove browser 
  - ionic cordova platform add browser
#  - MY_ENV=testing ionic serve